Add thumbcache parser
fox-it/dissect.thumbcache pull request #1
Opened 2022-10-27 09:29 UTC by Miauwkeru

(DIS-1352)

2022-10-27 14:01 UTC, Poeloe reviewed
Initial review comments

2022-10-27 14:26 UTC, cecinestpasunepipe requested changes

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/index.py
> +            additional_header_bytes = INDEX_ENTRIES.get(header.version) * 8
Use constant instead of literal 8 for readability?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache.py
> +    def __init__(self, path: Path, prefix="thumbcache") -> None:
prefix type, str?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/index.py
> +    def __init__(self, file: BinaryIO):
Consistency, you used -> None everywhere else...?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache_file.py
> +    def _get_header_type(self, file: BinaryIO):
return type?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache_file.py
> +    def __getitem__(self, key: int):
return type?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache_file.py
> +            file.read(8)
Constants?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache_file.py
> +    def _get_header(self, thumbnail_type: ThumbnailType):
Return type?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on tests/test_thumbcachefile.py
> +    thumbcache_file[0x18].hash == "e84eb8f951bc2409"
no assert here?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/index.py
> +    def _select_header(self):
return type?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/index.py
> +    def header(self):
return type?

2022-10-27 14:26 UTC, cecinestpasunepipe commented on dissect/thumbcache/index.py
> +    def header(self):
return type?

2022-10-28 09:40 UTC, cecinestpasunepipe requested changes

2022-10-28 09:40 UTC, cecinestpasunepipe commented on dissect/thumbcache/thumbcache_file.py
> +    def version(self) -> ThumbnailType:
Should there not be a more graceful error or check here? As a naive user I now might think the thumbcache plugin is broken? Although this might be a more general issue with Dissect. Do we have a distinction between internal exceptions and user exceptions (i.e. user did something wrong and receives a kindly worded notification) ?

![image](https://user-images.githubusercontent.com/110607403/198556601-00f43f42-c2a9-4250-81c4-17493038ebd1.png)

2022-10-28 10:29 UTC, Schamper requested changes

2022-10-28 10:29 UTC, Schamper commented on dissect/thumbcache/index.py
> +    def __init__(self, file: BinaryIO) -> None:
Maybe personal preference but `fh` over `file`?

2022-10-28 10:29 UTC, Schamper commented on dissect/thumbcache/index.py
> +        From windows 8.1 onward, the two fields seem use a 64-bit format field
```suggestion
        From Windows 8.1 onward, the two fields seem to use a 64-bit format field
```

2022-10-28 10:29 UTC, Schamper commented on dissect/thumbcache/index.py
> +    def __init__(self, file: BinaryIO, type: ThumbnailType, data=[]) -> None:
Usually ill advised to use `[]` as default value since it's mutable. Rather do `data=None` followed by `self._data = data or []`.

2022-10-28 10:29 UTC, Schamper commented on dissect/thumbcache/thumbcache_file.py
> +    At least for windows 7: http://www.swiftforensics.com/2012/06/windows-7-thumbcache-hash-algorithm.html
```suggestion
    At least for Windows 7: http://www.swiftforensics.com/2012/06/windows-7-thumbcache-hash-algorithm.html
```

2022-10-28 13:57 UTC, Poeloe commented on tests/test_index.py
> +) -> None:
In the other code if've seen you not specifying the return type when None. For consistency, remove the one here :)
```suggestion
):
```

2022-10-28 13:59 UTC, Poeloe commented on tests/test_thumbcache.py
> +def thumbcache(path: str):
```suggestion
def thumbcache(path: str) -> Thumbcache:
```

2022-10-31 10:05 UTC, Schamper requested changes

2022-10-31 10:08 UTC, Schamper commented on dissect/thumbcache/tools/extract_images.py
> +        print("Please provide a file other than the idx file.")
`parser.exit(msg)` would give you a nice way to do this.

2022-11-02 12:56 UTC, Schamper commented
There's currently no `__init__.py` at all, but can you add all the useful classes in there in `__all__`?

2022-11-02 15:08 UTC, Schamper approved these changes

2022-11-03 10:09 UTC, cecinestpasunepipe approved these changes

2022-11-03 10:18 UTC, merged